---
- name: Make user
  hosts: waddle
  become: true

  tasks:
    - name: Cronjob
      ansible.builtin.cron:
        name: Print things to file
        minute: "*/2"
        hour: "*"
        job: "echo Imaaaaaaaaaginaaaaaatioooooon >> /home/drew/Desktop/cronjob.txt"
        user: drew
        cron_file: wahoo
        state: present