---
- name: Stand up webserver
  hosts: waddle
 
  roles:
    - webserver
    - name: rhel-system-roles.storage
        storage_pools:
        - name: vg_web
          type: lvm
          disks:
            - /dev/vdb
          volumes: 
            - name: lv_uploads
              size: 256m
              fs_type: xfs
              state: present
              mount_point: "/var/www/html/uploads"
            - name: lv_content
              size: 128m
              mount_point: "/var/www/html/content"
              fs_type: xfs
              state: present