---
- name: Set up load balancer
  community.general.oneanddone_load_balancer:
    auth_token: oneandone_private_api_key
    name: Ansible Load balancer
    description: Test load balancer
    persistence: true
    persistence_time: 900
    method: ROUND_ROBIN
    datacenter: US
    rules:
      -
        protocol: TCP
        port_balancer: 80
        port_server: 80
        source: 0.0.0.0
    wait: true
    wait_timeout: 500